-- Adjustments to eden after installation
-- Update the address and organization tables
DELETE FROM address;
DELETE FROM org;
DELETE FROM business;
DELETE FROM legal;
DELETE FROM inventory;
DELETE FROM enterprise;
DELETE FROM mdm_tax_region;

INSERT INTO mdm_tax_region (mdm_tax_region_id,country_code,state,city,tax_region_name,tax_jurisdiction,description,status,created_by,creation_date,last_update_by,last_update_date) VALUES
(1,'USA','AL',NULL,'US-AL','state','Alabama','active',0,NOW(),0,NOW())
,(2,'USA','AK',NULL,'US-AK','state','Alaska','active',0,NOW(),0,NOW())
,(3,'USA','AZ',NULL,'US-AZ','state','Arizona','active',0,NOW(),0,NOW())
,(4,'USA','AR',NULL,'US-AR','state','Arkansas','active',0,NOW(),0,NOW())
,(5,'USA','CA',NULL,'US-CA','state','California','active',0,NOW(),0,NOW())
,(6,'USA','CO',NULL,'US-CO','state','Colorado','active',0,NOW(),0,NOW())
,(7,'USA','CT',NULL,'US-CT','state','Connecticut','active',0,NOW(),0,NOW())
,(8,'USA','DE',NULL,'US-DE','state','Delaware','active',0,NOW(),0,NOW())
,(9,'USA','FL',NULL,'US-FL','state','Florida','active',0,NOW(),0,NOW())
,(10,'USA','GA',NULL,'US-GA','state','Georgia','active',0,NOW(),0,NOW())
,(11,'USA','HI',NULL,'US-HI','state','Hawaii','active',0,NOW(),0,NOW())
,(12,'USA','ID',NULL,'US-ID','state','Idaho','active',0,NOW(),0,NOW())
,(13,'USA','IL',NULL,'US-IL','state','Illinois','active',0,NOW(),0,NOW())
,(14,'USA','IN',NULL,'US-IN','state','Indiana','active',0,NOW(),0,NOW())
,(15,'USA','IA',NULL,'US-IA','state','Iowa','active',0,NOW(),0,NOW())
,(16,'USA','KS',NULL,'US-KS','state','Kansas','active',0,NOW(),0,NOW())
,(17,'USA','KY',NULL,'US-KY','state','Kentucky','active',0,NOW(),0,NOW())
,(18,'USA','LA',NULL,'US-LA','state','Louisiana','active',0,NOW(),0,NOW())
,(19,'USA','ME',NULL,'US-ME','state','Maine','active',0,NOW(),0,NOW())
,(20,'USA','MD',NULL,'US-MD','state','Maryland','active',0,NOW(),0,NOW())
,(21,'USA','MA',NULL,'US-MA','state','Massachusetts','active',0,NOW(),0,NOW())
,(22,'USA','MI',NULL,'US-MI','state','Michigan','active',0,NOW(),0,NOW())
,(23,'USA','MN',NULL,'US-MN','state','Minnesota','active',0,NOW(),0,NOW())
,(24,'USA','MS',NULL,'US-MS','state','Mississippi','active',0,NOW(),0,NOW())
,(25,'USA','MO',NULL,'US-MO','state','Missouri','active',0,NOW(),0,NOW())
,(26,'USA','MT',NULL,'US-MT','state','Montana','active',0,NOW(),0,NOW())
,(27,'USA','NE',NULL,'US-NE','state','Nebraska','active',0,NOW(),0,NOW())
,(28,'USA','NV',NULL,'US-NV','state','Nevada','active',0,NOW(),0,NOW())
,(29,'USA','NH',NULL,'US-NH','state','New Hampshire','active',0,NOW(),0,NOW())
,(30,'USA','NJ',NULL,'US-NJ','state','New Jersey','active',0,NOW(),0,NOW())
,(31,'USA','NM',NULL,'US-NM','state','New Mexico','active',0,NOW(),0,NOW())
,(32,'USA','NY',NULL,'US-NY','state','New York','active',0,NOW(),0,NOW())
,(33,'USA','NC',NULL,'US-NC','state','North Carolina','active',0,NOW(),0,NOW())
,(34,'USA','ND',NULL,'US-ND','state','North Dakota','active',0,NOW(),0,NOW())
,(35,'USA','OH',NULL,'US-OH','state','Ohio','active',0,NOW(),0,NOW())
,(36,'USA','OK',NULL,'US-OK','state','Oklahoma','active',0,NOW(),0,NOW())
,(37,'USA','OR',NULL,'US-OR','state','Oregon','active',0,NOW(),0,NOW())
,(38,'USA','PA',NULL,'US-PA','state','Pennsylvania','active',0,NOW(),0,NOW())
,(39,'USA','RI',NULL,'US-RI','state','Rhode Island','active',0,NOW(),0,NOW())
,(40,'USA','SC',NULL,'US-SC','state','South Carolina','active',0,NOW(),0,NOW())
,(41,'USA','SD',NULL,'US-SD','state','South Dakota','active',0,NOW(),0,NOW())
,(42,'USA','TN',NULL,'US-TN','state','Tennessee','active',0,NOW(),0,NOW())
,(43,'USA','TX',NULL,'US-TX','state','Texas','active',0,NOW(),0,NOW())
,(44,'USA','UT',NULL,'US-UT','state','Utah','active',0,NOW(),0,NOW())
,(45,'USA','VT',NULL,'US-VT','state','Vermont','active',0,NOW(),0,NOW())
,(46,'USA','VA',NULL,'US-VA','state','Virginia','active',0,NOW(),0,NOW())
,(47,'USA','WA',NULL,'US-WA','state','Washington','active',0,NOW(),0,NOW())
,(48,'USA','WV',NULL,'US-WV','state','West Virginia','active',0,NOW(),0,NOW())
,(49,'USA','WI',NULL,'US-WI','state','Wisconson','active',0,NOW(),0,NOW())
,(50,'USA','WY',NULL,'US-WY','state','Wyoming','active',0,NOW(),0,NOW())
,(51,'USA','PR',NULL,'US-PR','state','Puerto Rico','active',0,NOW(),0,NOW())
,(52,'USA','Guam',NULL,'US-Guam','state','Guam','active',0,NOW(),0,NOW())
,(53,'USA','DC','Washington','US-DC-Washington','city','Washington, DC','active',0,NOW(),0,NOW())
;

INSERT INTO address (address_id,mdm_tax_region_id,address_name,description,phone,email,website,address,country,postal_code,default_cb,status,usage_type,rev_number,created_by,creation_date,last_update_by,last_update_date) VALUES
(1,38,'HQ','Eden Headquarters','215-702-4260','','http://csinfo.cairn.edu/eden','200 Manor Ave'+char(13)+char(10)+'Langhorne, PA','USA','19047',0,'enabled','enabled',0,0,NOW(),0,NOW())
;

INSERT INTO org (org_id,org,code,type,description,enterprise_org_id,legal_org_id,business_org_id,inventory_org_id,status,address_id,created_by,creation_date,last_update_by,last_update_date) VALUES
(1,'EDEN HQ','HQ','ENTERPRISE','Eden from the Rock',1,NULL,NULL,NULL,'ACTIVE',1,0,NOW(),0,NOW())
,(2,'FARM001','F001','BUSINESS_ORG','Eden Produce PA 1',1,NULL,2,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(3,'FARM002','F002','BUSINESS_ORG','Eden Produce PA 2',1,NULL,3,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(4,'FARM003','F003','BUSINESS_ORG','Eden Dairy PA 3',1,NULL,4,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(5,'FARM004','F004','BUSINESS_ORG','Eden Produce NJ 1',1,NULL,5,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(6,'FARM005','F005','BUSINESS_ORG','Eden Produce NJ 2',1,NULL,6,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(7,'FARM006','F006','BUSINESS_ORG','Eden Fish NJ 3',1,NULL,7,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(8,'FARM007','F007','BUSINESS_ORG','Eden Produce NY 1',1,NULL,8,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(9,'FARM008','F008','BUSINESS_ORG','Eden Fish NY 2',1,NULL,9,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(10,'FARM009','F009','BUSINESS_ORG','Eden Produce OH 1',1,NULL,10,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(11,'FARM010','F010','BUSINESS_ORG','Eden Produce IN 1',1,NULL,11,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(12,'FARM011','F011','BUSINESS_ORG','Eden Produce MI 1',1,NULL,12,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(13,'FARM012','F012','BUSINESS_ORG','Eden Produce WI 1',1,NULL,13,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(14,'FARM013','F013','BUSINESS_ORG','Eden Produce MO 1',1,NULL,14,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(15,'FARM014','F014','BUSINESS_ORG','Eden Produce CA 1',1,NULL,15,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(16,'FARM015','F015','BUSINESS_ORG','Eden Produce CA 2',1,NULL,16,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(17,'FARM016','F016','BUSINESS_ORG','Eden Produce CA 3',1,NULL,17,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(18,'FARM017','F017','BUSINESS_ORG','Eden Fish CA 4',1,NULL,18,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(19,'FARM018','F018','BUSINESS_ORG','Eden Fish AK 1',1,NULL,19,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(20,'FARM019','F019','BUSINESS_ORG','Eden Grain KS 1',1,NULL,20,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(21,'FARM020','F020','BUSINESS_ORG','Eden Produce HI 1',1,NULL,21,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(22,'FARM021','F021','BUSINESS_ORG','Eden Produce GA 1',1,NULL,22,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(23,'FARM022','F022','BUSINESS_ORG','Eden Grain ID 1',1,NULL,23,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(24,'FARM023','F023','BUSINESS_ORG','Eden Fish WA 1',1,NULL,24,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(25,'FARM024','F024','BUSINESS_ORG','Eden Fish PR 1',1,NULL,25,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(26,'FARM025','F025','BUSINESS_ORG','Eden Fish ME 1',1,NULL,26,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(27,'FARM026','F026','BUSINESS_ORG','Eden Produce OR 1',1,NULL,27,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(28,'FARM027','F027','BUSINESS_ORG','Eden Produce OR 2',1,NULL,28,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(29,'FARM028','F028','BUSINESS_ORG','Eden Produce CO 1',1,NULL,29,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(30,'FARM029','F029','BUSINESS_ORG','Eden Produce Alberta 1',1,NULL,30,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(31,'FARM030','F030','BUSINESS_ORG','Eden Produce Kobe 1',1,NULL,31,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(32,'FARM031','F031','BUSINESS_ORG','Eden Produce Nice 1',1,NULL,32,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(33,'FARM032','F032','BUSINESS_ORG','Eden Produce Warsaw 1',1,NULL,33,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(34,'FARM033','F033','BUSINESS_ORG','Eden Produce Marijampole 1',1,NULL,34,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(35,'FARM034','F034','BUSINESS_ORG','Eden Produce Sicily 1',1,NULL,35,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(36,'FARM035','F035','BUSINESS_ORG','Eden Produce Lima 1',1,NULL,36,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(37,'REST036','R036','BUSINESS_ORG','Eden''s Bistro - Chicago',1,NULL,37,'ACTIVE',NULL,0,NOW(),0,NOW())
,(38,'REST037','R037','BUSINESS_ORG','Eden''s Bistro - Manhattan',1,NULL,38,'ACTIVE',NULL,0,NOW(),0,NOW())
,(39,'REST038','R038','BUSINESS_ORG','Eden''s Bistro - Buffalo',1,NULL,39,'ACTIVE',NULL,0,NOW(),0,NOW())
,(40,'REST039','R039','BUSINESS_ORG','Eden''s Bistro - Atlanta',1,NULL,40,'ACTIVE',NULL,0,NOW(),0,NOW())
,(41,'REST040','R040','BUSINESS_ORG','Eden''s Bistro - Sacramento',1,NULL,41,'ACTIVE',NULL,0,NOW(),0,NOW())
,(42,'REST041','R041','BUSINESS_ORG','Eden''s Bistro - Seattle',1,NULL,42,'ACTIVE',NULL,0,NOW(),0,NOW())
,(43,'REST042','R042','BUSINESS_ORG','Eden''s Bistro - Boston',1,NULL,43,'ACTIVE',NULL,0,NOW(),0,NOW())
,(44,'REST043','R043','BUSINESS_ORG','Eden''s Bistro - Miami',1,NULL,44,'ACTIVE',NULL,0,NOW(),0,NOW())
,(45,'REST044','R044','BUSINESS_ORG','Eden''s Bistro - Honolulu',1,NULL,45,'ACTIVE',NULL,0,NOW(),0,NOW())
,(46,'REST045','R045','BUSINESS_ORG','Eden''s Bistro - Denver',1,NULL,46,'ACTIVE',NULL,0,NOW(),0,NOW())
,(47,'FARM046','F046','BUSINESS_ORG','Eden Produce Rio 1',1,NULL,47,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(48,'FARM047','F047','BUSINESS_ORG','Eden Produce Santiago 1',1,NULL,48,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
,(49,'FARM048','F048','BUSINESS_ORG','Eden Fish Abidijan 1',1,NULL,49,NULL,'ACTIVE',NULL,0,NOW(),0,NOW())
;

INSERT INTO enterprise (enterprise_id,org_id,status,created_by,creation_date,last_update_by,last_update_date) VALUES
(1,1,'active',0,NOW(),0,NOW());

INSERT INTO business (business_id,org_id,business_org_type,status,enterprise_org_id,created_by,creation_date,last_update_by,last_update_date) VALUES
(2,2,'Owned Farm','active',1,0,NOW(),0,NOW())
,(3,3,'Owned Farm','active',1,0,NOW(),0,NOW())
,(4,4,'Franchise Farm','active',1,0,NOW(),0,NOW())
,(5,5,'Owned Farm','active',1,0,NOW(),0,NOW())
,(6,6,'Franchise Farm','active',1,0,NOW(),0,NOW())
,(7,7,'Owned Fishery','active',1,0,NOW(),0,NOW())
,(8,8,'Franchise Farm','active',1,0,NOW(),0,NOW())
,(9,9,'Owned Fishery','active',1,0,NOW(),0,NOW())
,(10,10,'Owned Farm','active',1,0,NOW(),0,NOW())
,(11,11,'Owned Farm','active',1,0,NOW(),0,NOW())
,(12,12,'Owned Farm','active',1,0,NOW(),0,NOW())
,(13,13,'Owned Farm','active',1,0,NOW(),0,NOW())
,(14,14,'Owned Farm','active',1,0,NOW(),0,NOW())
,(15,15,'Owned Farm','active',1,0,NOW(),0,NOW())
,(16,16,'Franchise Farm','active',1,0,NOW(),0,NOW())
,(17,17,'Franchise Farm','active',1,0,NOW(),0,NOW())
,(18,18,'Franchise Fishery','active',1,0,NOW(),0,NOW())
,(19,19,'Franchise Fishery','active',1,0,NOW(),0,NOW())
,(20,20,'Franchise Farm','active',1,0,NOW(),0,NOW())
,(21,21,'Franchise Farm','active',1,0,NOW(),0,NOW())
,(22,22,'Franchise Farm','active',1,0,NOW(),0,NOW())
,(23,23,'Franchise Farm','active',1,0,NOW(),0,NOW())
,(24,24,'Franchise Fishery','active',1,0,NOW(),0,NOW())
,(25,25,'Franchise Fishery','active',1,0,NOW(),0,NOW())
,(26,26,'Franchise Fishery','active',1,0,NOW(),0,NOW())
,(27,27,'Franchise Farm','active',1,0,NOW(),0,NOW())
,(28,28,'Franchise Farm','active',1,0,NOW(),0,NOW())
,(29,29,'Franchise Farm','active',1,0,NOW(),0,NOW())
,(30,30,'Franchise Farm International','active',1,0,NOW(),0,NOW())
,(31,31,'Franchise Farm International','active',1,0,NOW(),0,NOW())
,(32,32,'Franchise Farm International','active',1,0,NOW(),0,NOW())
,(33,33,'Franchise Farm International','active',1,0,NOW(),0,NOW())
,(34,34,'Franchise Farm International','active',1,0,NOW(),0,NOW())
,(35,35,'Franchise Farm International','active',1,0,NOW(),0,NOW())
,(36,36,'Owned Restaurant','active',1,0,NOW(),0,NOW())
,(37,37,'Owned Restaurant','active',1,0,NOW(),0,NOW())
,(38,38,'Owned Restaurant','active',1,0,NOW(),0,NOW())
,(39,39,'Franchise Restaurant','active',1,0,NOW(),0,NOW())
,(40,40,'Franchise Restaurant','active',1,0,NOW(),0,NOW())
,(41,41,'Franchise Restaurant','active',1,0,NOW(),0,NOW())
,(42,42,'Franchise Restaurant','active',1,0,NOW(),0,NOW())
,(43,43,'Franchise Restaurant','active',1,0,NOW(),0,NOW())
,(44,44,'Franchise Restaurant','active',1,0,NOW(),0,NOW())
,(45,45,'Franchise Restaurant','active',1,0,NOW(),0,NOW())
,(46,46,'Franchise Restaurant','active',1,0,NOW(),0,NOW())
,(47,47,'Franchise Farm International','active',1,0,NOW(),0,NOW())
,(48,48,'Franchise Farm International','active',1,0,NOW(),0,NOW())
,(49,49,'Franchise Fishery International','active',1,0,NOW(),0,NOW())
;

INSERT INTO user_group_access(user_group_code,ord_id,access_level,created_by,creation_date,last_update_by,last_update_date) VALUES
('ALL_ORG_BOTH',1,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',2,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',3,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',4,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',5,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',6,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',7,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',8,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',9,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',10,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',11,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',12,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',13,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',14,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',15,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',16,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',17,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',18,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',19,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',20,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',21,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',22,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',23,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',24,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',25,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',26,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',27,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',28,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',29,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',30,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',31,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',32,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',33,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',34,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',35,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',36,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',37,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',38,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',39,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',40,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',41,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',42,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',43,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',44,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',45,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',46,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',47,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',48,9,0,NOW(),0,NOW())
,('ALL_ORG_BOTH',49,9,0,NOW(),0,NOW())
;